# Use custom format
format = """
[|](bold blue)\
$directory\
$git_branch \
$git_commit\
$git_state\
$git_metrics\
$git_status
[└─>](bold blue) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Set 'catpuccin_mocha' as custom color palette
palette = "catppuccin_mocha"

[directory]
style = 'bold rosewater'
truncation_length = 8
truncation_symbol = '…/'
# before_repo_root_style = 'green'
repo_root_style = 'bold pink'

[git_branch]
style = 'bold blue'
symbol = ''

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
